[package]
name = "timescale_analytics"
version = "0.2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = []
pg10 = ["pgx/pg10", "pgx-tests/pg10"]
pg11 = ["pgx/pg11", "pgx-tests/pg11"]
pg12 = ["pgx/pg12", "pgx-tests/pg12"]
pg13 = ["pgx/pg13", "pgx-tests/pg13"]
pg_test = ["approx"]

[dependencies]
pgx = {git="https://github.com/JLockerman/pgx.git", branch="timescale"}
pgx-macros = {git="https://github.com/JLockerman/pgx.git", branch="timescale"}
tdigest = {path="../crates/t-digest"}
hyperloglog = {path="../crates/hyperloglog"}
uddsketch = {path="../crates/udd-sketch"}
counter-agg = {path="../crates/counter-agg"}
time_weighted_average = {path="../crates/time-weighted-average"}
asap = {path="../crates/asap"}

approx = {version = "0.4.0", optional = true}
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
paste = "1.0"
rand = "0.8.3"
rand_distr = "0.4.0"

[dependencies.flat_serialize]
git = "https://github.com/JLockerman/flat_serialize"
rev = "41c100c"

[dependencies.flat_serialize_macro]
git = "https://github.com/JLockerman/flat_serialize"
rev = "41c100c"

[dev-dependencies]
pgx-tests = {git="https://github.com/JLockerman/pgx.git", branch="timescale"}
approx = "0.4.0"
