[workspace]
resolver = "2"

members = [
    "extension",
    "crates/encodings",
    "crates/t-digest",
    "crates/hyperloglog",
    "crates/udd-sketch",
    "crates/time-weighted-average",
    "tools/post-install",
    "tools/sql-doctester",
    "tools/testrunner",
    "crates/asap",
    "crates/counter-agg",
    "crates/time-series",
]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
debug = true
