name: nightly

on:
  pull_request:
    paths:
      - 'docker/nightly/**'
  workflow_dispatch:
  schedule:
    # we build at 8am UTC, 3am Eastern, midnight Pacific
    - cron:  '0 8 * * 1-4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-debian-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-debian

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build
      #   id: tester_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     target: toolkit-tools
      #     push: false
      #     load: true
      #     context: .
      #     file: ./docker/nightly/Dockerfile
      #     tags: timescaledev/timescaledb-toolkit:tester
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache

      # - name: Run Tests
      #   run: |
      #       docker run -d --name toolkit_test -e POSTGRES_HOST_AUTH_METHOD=trust timescaledev/timescaledb-toolkit:tester
      #       docker exec toolkit_test /bin/bash -c 'PATH=\"${PATH}:/root/.cargo/bin\" \
      #         && cd /rust/timescaledb-analytics/crates \
      #         && cargo test --release --workspace --exclude timescaledb_toolkit'
      #       docker stop toolkit_test
      # TODO we also want to run our extension tests, but we don't want to restart the DB, need a pgx patch

      #TODO run doctests

      - name: Push
        id: image_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ startsWith(github.event_name, 'cron') }}
          context: .
          file: ./docker/nightly/Dockerfile
          tags: timescaledev/timescaledb-toolkit:nightly

      - name: Image digest
        run: echo ${{ steps.image_build.outputs.digest }}
